### ISSUE TITLE
Python3 bytes literals

### ISSUE THREAD

**Issue by matthewgadd** [matthewgadd/RobotCarDataset-Scraper#2]
Hello,
First I would like to thank you for your work on this dataset.

When just doing a git clone and running the provided command with my username and password I get the following error:

```
ScrapeMRGDatashare is starting...
got num_datasets: 1
got num_file_patterns: 1
got csrf_middleware_token: 8fAsEHXhYm3FOIS9zWZo9RnptirdfVGFfVGvpCMERgoB1CxZQTwhCAHZ9LaVBVrT
got status_code: 200
Logged in!
num_chunks_in_period: 0, period_seconds: 600
creating dataset: 2014-05-06-12-54-54
requesting file_url: http://mrgdatashare.robots.ox.ac.uk:80/download/?filename=datasets/2014-05-06-12-54-54/2014-05-06-12-54-54_vo.tar
got status_code: 200
downloading local_file_path: /mnt/c/Users/fbartocc/Downloads/2014-05-06-12-54-54/2014-05-06-12-54-54_vo.tar
Traceback (most recent call last):
  File "scrape_mrgdatashare.py", line 990, in <module>
    file_was_found = scraper.scrape(url_handler)
  File "scrape_mrgdatashare.py", line 454, in scrape
    if "File not found." in chunk:
TypeError: a bytes-like object is required, not 'str'
```

Correct me if I am wrong, but just changing ``"File not found."`` to ``b"File not found."`` would do the trick.

_Originally posted by @F-Barto in https://github.com/matthewgadd/RobotCarDataset-Scraper/issues/1#issuecomment-473562469_

**Comment by matthewgadd** [comment]
Ah, I should mention in the README that the code is tested for Python2 only
I have also just pushed on commit df9289c03a8d51193a41c50e2e25b2f2ec60ebfe this suggestion, thank you very much.
Although there may be some other issues that arise from using Python3
